/**
 * Modelo de la tabla dbo.Catastro
 * Transcrito de script_creacion_bd_ElManzano_062026.sql
 */

const { DataTypes } = require('sequelize');

module.exports = (sequelize) => {
  const Catastro = sequelize.define('Catastro', {
    IdTrans: { type: DataTypes.INTEGER, allowNull: false, primaryKey: true, autoIncrement: true },
    ID_CATASTRO: { type: DataTypes.STRING(6), allowNull: true },
    IDENTIFICADOR: { type: DataTypes.STRING(5), allowNull: true },
    Codigo: { type: DataTypes.STRING(7), allowNull: true },
    CODIGO_CALLE: { type: DataTypes.STRING(15), allowNull: true },
    CODIGO_POSTAL_AUXILIAR: { type: DataTypes.STRING(8), allowNull: true },
    NRO_RENTA: { type: DataTypes.STRING(30), allowNull: true },
    CALLE_NOCOD: { type: DataTypes.STRING(30), allowNull: true },
    NUMERACION_CALLE: { type: DataTypes.STRING(5), allowNull: true },
    PISO: { type: DataTypes.STRING(4), allowNull: true },
    BARRIO: { type: DataTypes.STRING(30), allowNull: true },
    DEPARTAMENTO: { type: DataTypes.STRING(4), allowNull: true },
    ESQUINA_MEDIAL: { type: DataTypes.STRING(2), allowNull: true },
    SUPERFICIE_TERRENO: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    COEFICIENTE_FRENTE_FONDO: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    PORCENTAJE_COPROPIEDAD: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    DESIGNACION_OFICIAL: { type: DataTypes.STRING(40), allowNull: true },
    FOLIO1: { type: DataTypes.STRING(30), allowNull: true },
    ANO1: { type: DataTypes.STRING(4), allowNull: true },
    FOLIO2: { type: DataTypes.STRING(30), allowNull: true },
    ANO2: { type: DataTypes.STRING(4), allowNull: true },
    CUENTA_LOTEO: { type: DataTypes.STRING(50), allowNull: true },
    NOMBRE_ESTABLECIMIENTO: { type: DataTypes.STRING(50), allowNull: true },
    NRO_MATRICULA_FOLIO_REAL: { type: DataTypes.STRING(30), allowNull: true },
    BALDIO_EDIFICADO: { type: DataTypes.STRING(20), allowNull: true },
    BASE_IMPONIBLE: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    TASACION_TERRENO: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    NRO_ESCRITURA: { type: DataTypes.STRING(30), allowNull: true },
    REGISTRO: { type: DataTypes.STRING(30), allowNull: true },
    DATO1: { type: DataTypes.STRING(30), allowNull: true },
    DATO2: { type: DataTypes.STRING(30), allowNull: true },
    DATO3: { type: DataTypes.STRING(60), allowNull: true },
    METROS_FRENTE: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    FRENTE_CONTRIBUCION: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    TORRE: { type: DataTypes.STRING(30), allowNull: true },
    COEF_IRREGULARIDAD: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    VALOR_TERRENO: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    VALOR_EDIFICADO: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    EJIDO: { type: DataTypes.STRING(4), allowNull: true },
    FEC_ESCRITURA: { type: DataTypes.DATE, allowNull: true },
    CODIGO_POSTAL_AMPLIADO: { type: DataTypes.STRING(14), allowNull: true },
    CONDICION_TERRENO: { type: DataTypes.STRING(4), allowNull: true },
    METROS_FONDO: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
    UNIDADES_LOCATIVAS: { type: DataTypes.INTEGER, allowNull: true },
    CODIGO_POSTAL_SUFIJO: { type: DataTypes.STRING(3), allowNull: true },
    Fecha: { type: DataTypes.DATE, allowNull: true },
    LIQUIDA: { type: DataTypes.STRING(1), allowNull: true },
    CLAVE_BIEN: { type: DataTypes.STRING(50), allowNull: true },
    EXENCION: { type: DataTypes.STRING(4), allowNull: true },
    FechaAlta: { type: DataTypes.DATEONLY, allowNull: true },
    DEP: { type: DataTypes.STRING(2), allowNull: true },
    PED: { type: DataTypes.STRING(2), allowNull: true },
    PUE: { type: DataTypes.STRING(2), allowNull: true },
    CIR: { type: DataTypes.STRING(2), allowNull: true },
    SEC: { type: DataTypes.STRING(2), allowNull: true },
    MAN: { type: DataTypes.STRING(3), allowNull: true },
    PAR: { type: DataTypes.STRING(3), allowNull: true },
    PH: { type: DataTypes.STRING(5), allowNull: true },
    DV: { type: DataTypes.INTEGER, allowNull: true },
    DOMINIO: { type: DataTypes.STRING(20), allowNull: true },
    FechaBaja: { type: DataTypes.DATE, allowNull: true },
    MOF: { type: DataTypes.STRING(3), allowNull: true },
    LOF: { type: DataTypes.STRING(3), allowNull: true },
    Descuento: { type: DataTypes.DECIMAL(19, 4), allowNull: true },
  }, {
    tableName: 'Catastro',
    schema: 'dbo',
    timestamps: false,
  });

  return Catastro;
};
